import { S as SvelteComponent, i as init, s as safe_not_equal, f as element, c as insert, n as noop, d as detach } from './index-767987fb.js';

/* src\second.svelte generated by Svelte v3.9.1 */

function create_fragment(ctx) {
	var h2;

	return {
		c() {
			h2 = element("h2");
			h2.textContent = "SECOND!";
		},

		m(target, anchor) {
			insert(target, h2, anchor);
		},

		p: noop,
		i: noop,
		o: noop,

		d(detaching) {
			if (detaching) {
				detach(h2);
			}
		}
	};
}

class Second extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, []);
	}
}

export default Second;
//# sourceMappingURL=second.js.map
